import { useState, useEffect } from 'react'
import { Phone, Mail, ArrowRight } from 'lucide-react'
import Loading from '../components/Loading'
import './landing.css'

function Landing() {
  const [scrolled, setScrolled] = useState(false)
  const [selectedDirector, setSelectedDirector] = useState(null)
  const [isLoading, setIsLoading] = useState(true)
  const [showLoader, setShowLoader] = useState(true)

  useEffect(() => {
    // Simulate loading time
    const timer = setTimeout(() => {
      setIsLoading(false)
    }, 1200)

    return () => clearTimeout(timer)
  }, [])

  useEffect(() => {
    if (!isLoading) {
      const fadeTimer = setTimeout(() => setShowLoader(false), 500)
      return () => clearTimeout(fadeTimer)
    }
  }, [isLoading])

  useEffect(() => {
    const handleScroll = () => {
      setScrolled(window.scrollY > 50)
    }
    window.addEventListener('scroll', handleScroll)
    return () => window.removeEventListener('scroll', handleScroll)
  }, [])

  // Scroll-triggered animations
  useEffect(() => {
    const observerOptions = {
      threshold: 0.1,
      rootMargin: '0px 0px -50px 0px'
    }

    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          entry.target.classList.add('visible')
          observer.unobserve(entry.target)
        }
      })
    }, observerOptions)

    // Small delay to ensure DOM is ready
    const timeoutId = setTimeout(() => {
      const animatedElements = document.querySelectorAll('.animate-on-scroll')
      animatedElements.forEach((el) => observer.observe(el))
    }, 100)

    return () => {
      clearTimeout(timeoutId)
      const animatedElements = document.querySelectorAll('.animate-on-scroll')
      animatedElements.forEach((el) => observer.unobserve(el))
    }
  }, [selectedDirector]) // Re-run when modal opens/closes

  const directors = [
    {
      id: 1,
      name: 'YV Ratna Kumar',
      role: 'Chairman & Managing Director',
      initials: 'YV',
      image: 'https://static.wixstatic.com/media/5c0589_9b1fbdcf6c874a76aa7afdd40aab8c38~mv2.jpg',
      bio: `Leading a team of unusual talents towards a dream of achieving unique objective is a trait of a visionary. Born with a desire to make a difference, Mr. Y.V. Ratna Kumar, is the Founder, Chairman & Managing Director of M/s APIMS INDIA PRIVATE LIMITED Pvt Ltd®.`,
      description: `He established the organization to give impetus to the infrastructure enhancement at regional level to start with and at national level at a later stage. Under his able leadership the company is witnessing exponential growth within very short period of time, which is a feat in itself.`,
      experience: `Formerly, Mr. Y.V. Ratna Kumar provided his services for various organizations including major multinational companies (MNC) worked as Director of ARSIN System Pvt Ltd (2006-2012) at Hyderabad. It was Sister concern firm of ARSIN Corporation, a California (USA) based Software firm.`,
      achievements: [
        'Over decade this esteemed firm showed Substantial growth under Leadership of Mr. Y.V.Ratna Kumar in Liasioning and several platforms like Facilitating',
        'Working for major projects of mega customers, handling various issues, solving critical labor issues',
        'Educating the clients on the latest improvements, talks on managerial sensitivity'
      ],
      keyAchievements: [
        'Infrastructure development across regions',
        'Job creation (direct & indirect)',
        'Strong leadership & vision'
      ],
      education: 'Mr. Y.V. Ratna Kumar studied Bachelor of technology from K L College of Engineering in Industrial Production engineering.',
      philosophy: 'Mr. Y.V. Ratna Kumar is one among the very few entrepreneurs who believe that the success of an organization cannot be measured by the bottom line alone. He measures the success by the number of direct and indirect jobs generated by the organization.'
    },
    {
      id: 2,
      name: 'Sambasiva Rao Nanduri',
      role: 'CEO / Director',
      initials: 'SN',
      image: 'https://static.wixstatic.com/media/5c0589_865e83f68cb441148f8ca26ce6b7bab9~mv2.jpeg',
      bio: `Shri N. Sambasiva Rao, IPS (Retd.) Former Director General of Police, Andhra Pradesh Former Vice Chairman & Managing Director, APSRTC Former CEO, Gangavaram Port Ltd. Senior Advisor, Adani Ports and SEZ Ltd.`,
      description: `Shri N. Sambasiva Rao, a distinguished officer of the 1984 batch of the Indian Police Service (Andhra Pradesh Cadre), has over four decades of exemplary service in public administration, law enforcement, and corporate leadership.`,
      experience: `An alumnus of the Indian Institute of Technology, Kanpur (M.Tech. – Mechanical Engineering), he has seamlessly combined technical insight with strategic leadership throughout his career. His professional journey spans critical assignments in policing, disaster management, transportation, and corporate governance.`,
      positions: [
        'Director General of Police, Andhra Pradesh (2016–2017)',
        'Vice Chairman & Managing Director, APSRTC (2015–2016)',
        'Director General, State Disaster Response and Fire Services (2013–2015)',
        'Director, A.P. Police Academy (2010–2013)',
        'Commissioner of Police, Visakhapatnam City (2007–2010)',
        'Superintendent / DIG in various Districts and Directorates (1984–2007)'
      ],
      corporate: [
        'Chief Executive Officer, Gangavaram Port Ltd. (2018–2022)',
        'Senior Advisor, Adani Ports and SEZ Ltd. (2022–2023)'
      ],
      education: 'M.Tech. – Mechanical Engineering, Indian Institute of Technology (IIT), Kanpur',
      awards: [
        "President's Police Medal (PPM) – 2010",
        'Indian Police Medal (IPM) – 2000',
        'Antharik Suraksha Seva Pathak – 2004',
        'Five Commendation Rewards for Meritorious Service',
        'No Punishments – Impeccable Record of Conduct'
      ],
      keyAchievements: [
        'DGP Andhra Pradesh (2016-17)',
        'CEO Gangavaram Port',
        'IIT Kanpur Alumni'
      ],
      philosophy: `Widely respected for visionary leadership, ethical governance, and people-oriented approach, Shri Rao's career reflects a rare combination of discipline, analytical acumen, and developmental insight, inspiring excellence in both public service and the corporate sector.`
    },
    {
      id: 3,
      name: 'Srinivasulu Vemulapalli',
      role: 'Director',
      initials: 'SV',
      image: 'https://static.wixstatic.com/media/5c0589_6eb24dbb2d054575a51e7615fa0aead6~mv2.jpeg',
      bio: `Bachelor of Technology (B.Tech) in Mechanical Engineering (1988-1992) Graduated with a strong foundation in mechanical engineering principles, manufacturing processes, and industrial design, setting the stage for a career in high-precision engineering and infrastructure development.`,
      description: `Mr. Srinivasulu Vemulapalli began his career in advanced manufacturing, specializing in CNC tooling, precision engineering, and the production of high-quality components for industrial and defense applications. His expertise in precision machining has contributed to the development of critical infrastructure across multiple industries.`,
      experience: `Venturing into real estate, he established a strong foothold in land banking, pooling, and construction, building a portfolio of high-value land assets and development projects.`,
      achievements: [
        'Strategic Land Acquisitions: Identifying and securing prime real estate for large-scale commercial and residential projects',
        'Legal Clearances & Compliance: Ensuring all projects meet regulatory standards and land-use policies',
        'Civil Contracts & Infrastructure Expansion: Spearheading construction projects that contribute to urban and suburban development'
      ],
      associations: [
        {
          title: 'Association with Phoenix (Since 2003)',
          description: 'In 2003, Mr. Vemulapalli collaborated with Phoenix, playing a pivotal role in structuring high-value developments for top builders. His ability to connect leading developers with premium land opportunities has significantly shaped key real estate landscapes.'
        },
        {
          title: 'Formation of Squarespace Group (2021)',
          description: 'In 2021, he established Squarespace Group, a premier real estate investment and development company. The firm is focused on delivering innovative, sustainable, and high-return projects, solidifying its presence as a leader in modern real estate development.'
        }
      ],
      projects: [
        'Hindujas Land Development (2021-2022): Acquired 60 acres of Hindujas-owned land for a high-rise residential project, integrating modern urban living standards with premium architectural design',
        '233-Acre Landmark Acquisition (2022): Secured 233 acres for a luxury residential villa community and high-rise tower development, marking one of the most significant land acquisitions in his portfolio',
        'Spearheading master-planned projects that blend modern aesthetics, sustainable infrastructure, and high-end living spaces'
      ],
      keyAchievements: [
        'Squarespace Group Founder (2021)',
        '233-acre landmark project',
        '30+ years in real estate'
      ],
      philosophy: `With over three decades of experience spanning manufacturing, real estate development, and large-scale infrastructure investments, Mr. Srinivasulu Vemulapalli continues to be a driving force in shaping India's urban landscape. His expertise in strategic acquisitions, regulatory compliance, and high-quality developments has positioned him as a visionary leader in the real estate and construction sector.`
    },
    {
      id: 4,
      name: 'Ravindranath Bollineni',
      role: 'Director',
      initials: 'RB',
      image: 'https://static.wixstatic.com/media/5c0589_6ab0c3020afa453ba2fc7b01bc90d8c5~mv2.jpg',
      imagePosition: 'center 70%',
      bio: `Bollineni Ravindranath is a serial entrepreneur with 3 decades of business experience in various sectors, and a recognised technology leader known to craft the requisite strategic vision to achieve business goals.`,
      description: `His entrepreneurial endeavors coupled with his executive acumen, global team building, and technology deployment capabilities are credited for strong ROI and operational improvement. He is the Managing Director for TV5 NEWS, Co-Founder and Managing Director for NuZen Group, and built a responsive organization that consistently delivers results by aligning technology initiatives with business goals with substantial improvements to service delivery, standardisation, and business/systems performance.`,
      positions: [
        'Managing Director & Chief Editor, TV5 (A Popular Telugu News Channel)',
        'Co-Founder & Managing Director, NuZen HERBAL PVT LTD (Manufacturer of Herbal FMCG products)',
        'NuZen Industries PVT LTD. (Manufacturer & Exporter of Tobacco products)',
        'Managing Trustee, SHREYA FOUNDATION (A Non-profit Organisation)'
      ],
      achievements: [
        'Spearheaded the digital transformation of TV5 News with tech-driven journalism',
        'Built NuZen Herbal into a leading herbal FMCG brand with national recognition',
        'Expanded NuZen Industries into global markets for tobacco exports',
        'Founded OmObar Labs to lead digital infrastructure for real estate and institutional clients',
        'Modernized JHCHBS, setting benchmarks in cooperative housing management',
        'Led impactful community and welfare projects through Shreya Foundation'
      ],
      company: 'TV5, NuZen & OmObar Labs',
      industry: 'Digital Infrastructure',
      education: 'Bachelor of Engineering',
      keyAchievements: [
        'TV5 Digital Transformation',
        'NuZen Herbal National Brand',
        'JHCHBS President'
      ],
      philosophy: `In addition, he is also the President of Jubilee Hills Cooperative House Building Society (JHCHBS), one of the largest and most prestigious housing societies in India. Under his leadership, JHCHBS has witnessed significant improvements in infrastructure, transparency, and community engagement. His proactive approach to resident welfare has set new benchmarks for cooperative housing management. Through his efforts, Jubilee Hills has not only retained but elevated its status as one of Hyderabad's most sought-after residential localities.`
    },
    {
      id: 5,
      name: 'Ramadas Yarlagadda',
      role: 'Director',
      initials: 'RY',
      image: 'https://static.wixstatic.com/media/5c0589_316d4cb29fee4ed5b3652468a5cd586b~mv2.jpg',
      bio: `Mr. Y Ram Das is the Director of APIMS India Pvt. Ltd. His expertise is a perfect blend of strong theoretical base and practical exposure.`,
      description: `He brings along with him over three decades of experience as a Professor in Organic Chemistry in JKC College, Guntur and as an advisory member of various prestigious education institutes. He is a Gold Medalist in Msc (Organic Chemistry) from University of Jabalpur.`,
      experience: `As an erudite and most experienced personality, at APIMS he plays a crucial role in critical decision process.`,
      education: 'Gold Medalist in MSc (Organic Chemistry) from University of Jabalpur',
      positions: [
        'Professor in Organic Chemistry at JKC College, Guntur (3+ decades)',
        'Advisory member of various prestigious education institutes',
        'Director of APIMS India Pvt. Ltd.'
      ],
      keyAchievements: [
        'Gold Medal MSc (Organic Chemistry)',
        '30+ years in academia',
        'Multiple institution advisory roles'
      ],
      philosophy: `His deep understanding of education and strategic thinking brings valuable perspective to APIMS India's mission of contributing to India's development through informed investment decisions and strategic partnerships.`
    }
  ]

  return (
    <div className="landing-page">
      {showLoader && <Loading isFadingOut={!isLoading} />}
      {/* Navigation */}
      <nav className={`landing-nav ${scrolled ? 'scrolled' : ''}`}>
        <div className="landing-nav-container">
          <div className="landing-nav-logo">
            <img
              src="/apims-logo.png"
              alt="APIMS logo"
              className="landing-logo-img"
            />
            <span className="logo-text">APIMS</span>
          </div>
          <div className="landing-nav-links">
            <a href="#home">Home</a>
            <a href="#about">About</a>
            <a href="#services">Services</a>
            <a href="#directors">Leadership</a>
            <a href="#verticals">Verticals</a>
            <a href="#contact">Contact</a>
          </div>
          <a
            className="landing-nav-cta"
            href="mailto:apimsindia@gmail.com?subject=Hey%20APIMS%2C%20I%20have%20an%20idea.."
          >
            Get a Quote
          </a>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="landing-hero" id="home">
        <div className="hero-gradient"></div>
        <div className="hero-blur"></div>
        <div className="hero-content">
          <div className="hero-eyebrow">APIMS India Private Limited</div>
          <h1 className="hero-title">
            Building India's
            <br />
            <span className="gradient-text">Future Together</span>
          </h1>
          <p className="hero-subtitle">
            We identify lucrative investment opportunities across businesses, providing investors with sector,
            market, and geographic investment advice and strategies.
          </p>
          <div className="hero-ctas">
            <a href="#about" className="btn-glass">
              Learn More <ArrowRight size={18} />
            </a>
          </div>
          <div className="hero-contact">
            <a href="mailto:contact@apimsindia.com" className="contact-link">
              <Phone size={18} />
              <span>+91 99499 45699</span>
            </a>
            <span className="contact-separator">|</span>
            <a href="mailto:contact@apimsindia.com" className="contact-link">
              <Mail size={18} />
              <span>contact@apimsindia.com</span>
            </a>
          </div>
        </div>
      </section>

      {/* About Section */}
      <section className="landing-section section-about" id="about">
        <div className="section-container">
          <div className="section-header-center animate-on-scroll">
            <h2 className="section-title">Who We Are</h2>
            <p className="section-description">
              APIMS INDIA PRIVATE LIMITED is bringing Experience, Expertise and Network to grow and create
              wealth across India.
            </p>
          </div>
          <div className="about-content">
            <div className="about-card glass-card animate-on-scroll">
              <div className="about-icon">🎯</div>
              <h3>Our Vision</h3>
              <p>
                To be a catalyst in ushering in Prosperity, World Class Health, Education, and Superior Living
                Standards for the people of India and do so in an Eco-friendly manner to build a vibrant and
                sustainable state for future generations.
              </p>
            </div>
            <div className="about-card glass-card animate-on-scroll">
              <div className="about-icon">🚀</div>
              <h3>Our Approach</h3>
              <p>
                We believe in creating value for our clients and social impact through our services. We build
                capacity by passing on knowledge and expertise to our clients and guide them in forming
                partnerships that will help them to realize their potential and fulfill their goals.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Mission Section */}
      <section className="landing-section section-mission dark-section">
        <div className="section-container">
          <div className="mission-grid">
            <div className="mission-content animate-on-scroll">
              <div className="section-eyebrow">Our Mission</div>
              <h2 className="section-title-large">Building India brick by brick</h2>
              <p className="mission-text">
                Our Mission is to contribute our share of efforts to build India brick by brick, toward bringing
                in investments, technology and advice from world class pioneer industries and thereby gaining
                insight and benefits from their visions and experiences to unfold a golden, euphoric state, where
                dreams become realities and visions become visuals, helping us take our state on the golden
                pathway of building prosperous Smart and Green cities and villages.
              </p>
              <button className="btn-secondary-light">Learn More About Our Mission →</button>
            </div>
            <div className="mission-visual animate-on-scroll">
              <div className="mission-image-placeholder">
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* What We Do Section */}
      <section className="landing-section section-what-we-do" id="services">
        <div className="section-container">
          <div className="section-header-center animate-on-scroll">
            <div className="section-eyebrow">What We Do</div>
            <h2 className="section-title">Comprehensive Business Solutions</h2>
            <p className="section-description">
              APIMS offers sustained service on a long-term basis and assists its clients to improve their
              operating efficiency and profits; launch new projects, develop the business potential offered by new
              markets, services, products and new ways of doing business.
            </p>
          </div>
          <div className="solutions-grid">
            <div className="solution-card animate-on-scroll">
              <div className="solution-icon">💼</div>
              <h3>Financial Services</h3>
              <p>
                Expert guidance on working big and exploring new opportunities. We offer the widest range of
                services to business owners to help their finances run smoothly.
              </p>
            </div>
            <div className="solution-card animate-on-scroll">
              <div className="solution-icon">📊</div>
              <h3>Corporate Services</h3>
              <p>
                Comprehensive analysis and strategic planning to ensure proposals align with organizational
                realities and capabilities, delivering measurable results.
              </p>
            </div>
            <div className="solution-card animate-on-scroll">
              <div className="solution-icon">🎓</div>
              <h3>Training Programs</h3>
              <p>
                Integrated approach to internal leadership development through our Management Seminar Series,
                inviting organizations to enhance their team capabilities.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Board of Directors */}
      <section className="landing-section section-directors dark-section" id="directors">
        <div className="section-container">
          <div className="section-header-center animate-on-scroll">
            <div className="section-eyebrow">Leadership</div>
            <h2 className="section-title">Board of Directors</h2>
            <p className="section-description">
              Experienced leaders driving innovation and growth across industries
            </p>
          </div>
          <div className="directors-grid">
            {directors.map((director) => (
              <div 
                key={director.id} 
                className="director-card animate-on-scroll"
                onClick={() => setSelectedDirector(director)}
              >
                <div className="director-image">
                  {director.image ? (
                    <img
                      src={director.image}
                      alt={director.name}
                      style={{ objectPosition: director.imagePosition || 'center' }}
                    />
                  ) : (
                    <div className="director-placeholder">{director.initials}</div>
                  )}
                </div>
                <h3 className="director-name">{director.name}</h3>
                <p className="director-role">{director.role}</p>
                <button className="director-view-profile">View Profile</button>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Director Profile Modal */}
      {selectedDirector && (
        <div className="director-modal-overlay" onClick={() => setSelectedDirector(null)}>
          <div className="director-modal" onClick={(e) => e.stopPropagation()}>
            <button className="modal-close" onClick={() => setSelectedDirector(null)}>✕</button>

            {/* Flat sheet header (no colored bar) */}
            <div className="sheet-head">
              <div className="avatar-large">
                {selectedDirector.image ? (
                  <img
                    src={selectedDirector.image}
                    alt={selectedDirector.name}
                    style={{ objectPosition: selectedDirector.imagePosition || 'center' }}
                  />
                ) : (
                  selectedDirector.initials
                )}
              </div>
              <div className="titles">
                <h2>{selectedDirector.name}</h2>
                <p className="subtitle">{selectedDirector.role}</p>
              </div>
            </div>

            {/* Two-column body */}
            <div className="sheet-body">
              <div className="sheet-main">
                <div className="modal-section">
                  <h3>Professional Summary</h3>
                  <p>{selectedDirector.bio}</p>
                  {selectedDirector.description && <p>{selectedDirector.description}</p>}
                  {selectedDirector.experience && <p>{selectedDirector.experience}</p>}
                </div>

                {selectedDirector.positions && selectedDirector.positions.length > 0 && (
                  <div className="modal-section">
                    <h3>Key Appointments</h3>
                    <ul className="modal-list">
                      {selectedDirector.positions.map((pos, idx) => (
                        <li key={idx}>{pos}</li>
                      ))}
                    </ul>
                  </div>
                )}

                {selectedDirector.corporate && selectedDirector.corporate.length > 0 && (
                  <div className="modal-section">
                    <h3>Corporate & Advisory Roles</h3>
                    <ul className="modal-list">
                      {selectedDirector.corporate.map((corp, idx) => (
                        <li key={idx}>{corp}</li>
                      ))}
                    </ul>
                  </div>
                )}

                {selectedDirector.achievements && selectedDirector.achievements.length > 0 && (
                  <div className="modal-section">
                    <h3>Key Achievements</h3>
                    <ul className="modal-list">
                      {selectedDirector.achievements.map((achievement, idx) => (
                        <li key={idx}>{achievement}</li>
                      ))}
                    </ul>
                  </div>
                )}

                {selectedDirector.associations && selectedDirector.associations.length > 0 && (
                  <div className="modal-section">
                    <h3>Business Associations</h3>
                    {selectedDirector.associations.map((assoc, idx) => (
                      <div key={idx} className="association-item">
                        <h4>{assoc.title}</h4>
                        <p>{assoc.description}</p>
                      </div>
                    ))}
                  </div>
                )}

                {selectedDirector.projects && selectedDirector.projects.length > 0 && (
                  <div className="modal-section">
                    <h3>Major Projects</h3>
                    <ul className="modal-list">
                      {selectedDirector.projects.map((project, idx) => (
                        <li key={idx}>{project}</li>
                      ))}
                    </ul>
                  </div>
                )}

                {selectedDirector.philosophy && (
                  <div className="modal-section">
                    <h3>Leadership Philosophy</h3>
                    <p>{selectedDirector.philosophy}</p>
                  </div>
                )}
              </div>

              <aside className="sheet-aside">
                {selectedDirector.company && (
                  <div className="fact">
                    <div className="fact-label">Company</div>
                    <div className="fact-value">{selectedDirector.company}</div>
                  </div>
                )}
                {selectedDirector.industry && (
                  <div className="fact">
                    <div className="fact-label">Industry</div>
                    <div className="fact-value">{selectedDirector.industry}</div>
                  </div>
                )}
                {selectedDirector.keyAchievements && selectedDirector.keyAchievements.length > 0 && (
                  <div className="fact">
                    <div className="fact-label">Key Achievements</div>
                    <div className="fact-value">
                      {selectedDirector.keyAchievements.map((achievement, idx) => (
                        <div key={idx} className="fact-achievement">{achievement}</div>
                      ))}
                    </div>
                  </div>
                )}
                {selectedDirector.education && (
                  <div className="fact">
                    <div className="fact-label">Education</div>
                    <div className="fact-value">{selectedDirector.education}</div>
                  </div>
                )}
              </aside>
            </div>
          </div>
        </div>
      )}

      {/* Business Verticals */}
      <section className="landing-section section-verticals" id="verticals">
        <div className="section-container">
          <div className="section-header-center animate-on-scroll">
            <div className="section-eyebrow">Our Portfolio</div>
            <h2 className="section-title">Business Verticals</h2>
            <p className="section-description">
              Strategic investments across multiple high-growth sectors
            </p>
          </div>
          <div className="verticals-grid">
            {[
              { label: 'Infrastructure', desc: 'Building modern cities and transportation networks', img: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800&q=80' },
              { label: 'Media & Entertainment', desc: 'Digital content and broadcasting platforms', img: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&q=80' },
              { label: 'Food & Agro', desc: 'Sustainable agriculture and food processing', img: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=800&q=80' },
              { label: 'Tourism', desc: 'Hospitality and destination development', img: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=80' },
              { label: 'Power & Energy', desc: 'Renewable energy and grid infrastructure', img: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&q=80' },
              { label: 'Education', desc: 'Modern learning institutions and EdTech', img: 'https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?w=800&q=80' },
              { label: 'Ports & Logistics', desc: 'Maritime trade and supply chain solutions', img: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=800&q=80' },
              { label: 'Transport', desc: 'Public transit and mobility infrastructure', img: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&q=80' },
              { label: 'Mining', desc: 'Mineral extraction and resource management', img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80' },
              { label: 'Exports & Trading', desc: 'International trade and commerce', img: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80' },
            ].map(v => (
              <div key={v.label} className="vertical-card animate-on-scroll">
                <div className="vertical-media">
                  <img src={v.img} alt={v.label} className="vertical-image" />
                  <div className="vertical-overlay"></div>
                </div>
                <div className="vertical-body">
                  <h3 className="vertical-title">{v.label}</h3>
                  <p className="vertical-description">{v.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="landing-section section-cta">
        <div className="cta-container">
          <h2 className="cta-title">Ready to exceed your expectations?</h2>
          <p className="cta-description">
            Let's discuss how we can help you achieve your investment goals
          </p>
          <a href="mailto:contact@apimsindia.com" className="btn-primary-large">
            Get in Touch
          </a>
        </div>
      </section>

      {/* Footer */}
      <footer className="landing-footer" id="contact">
        <div className="footer-container">
          <div className="footer-grid">
            <div className="footer-col">
              <h4>APIMS INDIA</h4>
              <p>Private Limited</p>
              <p className="footer-tagline">
                Building prosperous, sustainable futures through strategic investments and partnerships.
              </p>
            </div>
            <div className="footer-col">
              <h5>Company</h5>
              <a href="#about">About Us</a>
              <a href="#services">Our Services</a>
              <a href="#directors">Leadership</a>
              <a href="#verticals">Verticals</a>
            </div>
            <div className="footer-col">
              <h5>Services</h5>
              <a href="#services">Financial Services</a>
              <a href="#services">Corporate Services</a>
              <a href="#services">Training Programs</a>
              <a href="#services">Consulting</a>
            </div>
            <div className="footer-col">
              <h5>Contact</h5>
              <a href="mailto:contact@apimsindia.com">+91 99499 45699</a>
              <a href="mailto:contact@apimsindia.com">contact@apimsindia.com</a>
              <div className="footer-social">
                <a
                  href="https://www.facebook.com/apimsindia"
                  aria-label="Facebook"
                  target="_blank"
                  rel="noreferrer"
                >
                  f
                </a>
                <a
                  href="https://x.com/apimsindia"
                  aria-label="Twitter"
                  target="_blank"
                  rel="noreferrer"
                >
                  𝕏
                </a>
                <a
                  href="https://www.linkedin.com/company/apims-india/"
                  aria-label="LinkedIn"
                  target="_blank"
                  rel="noreferrer"
                >
                  in
                </a>
              </div>
            </div>
          </div>
          <div className="footer-bottom">
            <p>&copy; 2025 APIMS INDIA Private Limited. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  )
}

export default Landing
